artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  train_file: artifacts/data_ingestion/train
  test_file: artifacts/data_ingestion/test
  validation_file: artifacts/data_ingestion/validation
  