artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  train_file: artifacts/data_ingestion/train
  test_file: artifacts/data_ingestion/test
  validation_file: artifacts/data_ingestion/validation
  

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]